version: '3.4'

volumes:
    mysql-data:

services:
    php:
        image: webdevops/php-apache:7.4
        container_name: laravel_employee_php
        volumes:
            - ./:/app
        environment:
            VIRTUAL_HOST: 'www.laravel.test'
            WEB_ALIAS_DOMAIN: 'www.laravel.test'
            WEB_DOCUMENT_ROOT: '/app/public'
        networks:
            - default
            - proxy

    db:
        image: mysql:8
        container_name: laravel_employee_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - LANG=C.UTF-8
            - TZ=Europe/Paris
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpwd
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - default

    adminer:
        image: clue/adminer
        container_name: laravel_employee_adminer
        links:
            - db
        expose:
            - "80"
        environment:
            # Add adminer URI in your /etc/host file
            VIRTUAL_HOST: 'adminer.laravel.test'
        networks:
            - default
            - proxy

networks:
    proxy:
        external: true
